// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA0AzVORMhpSJWCD68vTFgEQrTWuLCcDI',
    appId: '1:592957648231:web:290e11bcce2ed8f494d3c2',
    messagingSenderId: '592957648231',
    projectId: 'flutter-todo-ac942',
    authDomain: 'flutter-todo-ac942.firebaseapp.com',
    storageBucket: 'flutter-todo-ac942.firebasestorage.app',
    measurementId: 'G-NXJ7CJ0ELV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd5K92GEtdySp3F1WrpLePOSD7bTMFZ24',
    appId: '1:592957648231:android:04925c2fb05d326494d3c2',
    messagingSenderId: '592957648231',
    projectId: 'flutter-todo-ac942',
    storageBucket: 'flutter-todo-ac942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3RHHvjN8FGQiirQU0My7TXtT9WzQsrtA',
    appId: '1:592957648231:ios:c70b9f06c103685594d3c2',
    messagingSenderId: '592957648231',
    projectId: 'flutter-todo-ac942',
    storageBucket: 'flutter-todo-ac942.firebasestorage.app',
    iosBundleId: 'com.example.studyfirstudemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3RHHvjN8FGQiirQU0My7TXtT9WzQsrtA',
    appId: '1:592957648231:ios:c70b9f06c103685594d3c2',
    messagingSenderId: '592957648231',
    projectId: 'flutter-todo-ac942',
    storageBucket: 'flutter-todo-ac942.firebasestorage.app',
    iosBundleId: 'com.example.studyfirstudemy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA0AzVORMhpSJWCD68vTFgEQrTWuLCcDI',
    appId: '1:592957648231:web:1b72bec2eb7784ef94d3c2',
    messagingSenderId: '592957648231',
    projectId: 'flutter-todo-ac942',
    authDomain: 'flutter-todo-ac942.firebaseapp.com',
    storageBucket: 'flutter-todo-ac942.firebasestorage.app',
    measurementId: 'G-SW3T49EZWR',
  );

}